### PR TITLE
Allow for queries with filters that subset the scoped key.

### PR DESCRIPTION
**Pull request by matthewtole**
Modify the scoped key enforcement logic to allow for filters in the
query that are subsets of those in the scoped key.

For example, you can now create a scoped key for multiple applications
and then do a request for a single application.

### CODE REVIEW

**Comment by sarfata** [comment]
Please do add tests for this. You are absolutely right (cf JIRA) that this module should be better tested and this sounds/look complicated enough that some tests would be helpful.

**Comment by matthewtole** [comment]
Yup. Turns out tests are a _really_ good idea, especially if you discover you didn't write the code properly in the first place! 

How should I add the tests to this branch, considering the base tests are in another branch. Can I merge the test branch into this branch and then push to this remote branch?

**Comment by sarfata** [comment]
You can probably merge the tests to master and then merge master into your other feature branches.

**Comment by matthewtole** [comment]
Like that?

**Comment by sarfata** [comment]
LGTM! :+1:
Please merge and let me know when you want me to push this to the server.

**Comment by matthewtole** [comment]
I actually can't merge. I don't have any rights on this repository. As far as I'm concerned this can be made live now, it is fully compatible with the current developer portal Keen requests.

**Comment by sarfata** [comment]
merged and pushed!

**Comment by matthewtole** [comment]
Is it just me or is it not working...

**Comment by matthewtole** [comment]
Nevermind, it's working again.

**Pull request merged**
